name: perpus_unwahas_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.3.2
  get: 4.6.6
  get_storage: ^2.1.1
  http: ^1.2.1
  path_provider: ^2.1.3
  url_launcher: ^6.3.0
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logomanajemen.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
